<header style="padding:10px;background:#f9f9f9;border-top:3px solid #00b2b1"><img id="Teradata-logo" src="https://www.teradata.com/Teradata/Images/Rebrand/Teradata_logo-two_color.png" alt="Teradata" width="220" align="right" />

<p style = 'font-size:28px;font-family:Arial;color:#E37C4D'><b>VantageCloud Lake Edition Environment Automation</b></p>
<hr>

<br>

<p style = 'font-size:18px;font-family:Arial;color:#E37C4D'><b>Utilize common workflow engines to automate the deployment of enterprise systems configuration.</b></p>

<p style = 'font-size:16px;font-family:Arial'><b style = 'color:#00b2b1'>Teradata VantageCloud Lake Edition</b> has been designed from the ground-up with self-service as a foundational architectural design. Customers may start out with leveraging the Console UI for setup and configuration tasks, but will quickly move towards automation.</p>

<p style = 'font-size:16px;font-family:Arial'><b style = 'color:#00b2b1'>Apache Aiflow</b> is one of the most common workflow automation engines, and provides a wide array of capabilities for creating batch, recurrring, and on-demand automated workflows.  Airflow can leverage the open APIs available in VantageCloud Lake, using python, SQL, or REST interfaces.</p>

<img src='images/Apache_Airflow.png' width = '800'>

<hr>

<b style = 'font-size:28px;font-family:Arial;color:#E37C4D'>Summary Overview</b>

<p style = 'font-size:16px;font-family:Arial'>This demonstration utilizes a set of Python functions to automate a "enterprise looking" deployment of VantageCloud Lake, including key features such as:</p>

<ul style = 'font-size:16px;font-family:Arial'>
    <li><b>SYSDBA Role</b>.  A DBA responsible for overal Systems Administration</li>
    <li><b>Compute Group Admin</b>.  A "Departmental" Administrator responsible for creating and assigning Compute Cluster Resources</li>
    <li><b>User Hierarchy</b>.  Creation of users and groups of users into resource admins/support users, and business users/analysts.</li>
    <li><b>Database Hierarchy</b>.  Databases and objects with organized parent/child relationships</li>
    <li><b>Compute Resource Standards</b>.  Naming conventions for Compute Groups, Profiles, and Access Roles</li>
    <li><b>Common Role-Based permissions</b>.  Admins, Read-Only, Read/Write, etc.</li>
    </ul>
    
<hr>

<b style = 'font-size:28px;font-family:Arial;color:#E37C4D'>Demonstration Overview</b>

<p style = 'font-size:16px;font-family:Arial'>This demonstration consists of several assets that work in combination to illustrate environment automation:</p>
<ul style = 'font-size:16px;font-family:Arial'>
    <li><b>This Notebook</b>.  This notebook consists of the overview and introduction, as well as executable code for automating the deployment of of Lake resources.  Each cell is idempotent, so can be run and rerun to illustrate how to use SQL APIs for each high leel step.</li>
    <li><b>vars.json</b>.  A variable file which contains environment and hierarchy specifics; including the IP address and DBC credentials for logging into the deployed VCLE Account.  There is a great deal of additional information which controls the deployment; such as the number and types of clusters, users, databases, etc.</li>
    <li><b>Demo_Setup_Airflow_Python.py</b>.  The Apache Airflow python file.  This uses the Python Operators to execute the below code in an Airflow DAG with some amount of dependency chaining in the DAG.  Note, the vars.json file should be uploaded as "Variables" in Airflow after editing for the correct environment/hierarchy.</li>

<hr>

<b style = 'font-size:24px;font-family:Arial;color:#E37C4D'>Database Hierarchy</b>

<p style = 'font-size:16px;font-family:Arial'>The scripts combined with vars.json, will create the following structure in any new VCLE system:</p>


<ul style = 'font-size:16px;font-family:Arial'>
    <li>DBC
        <ul style = 'font-size:16px;font-family:Arial'>
            <li>SYSDBA
                <ul style = 'font-size:16px;font-family:Arial'>
                    <li>Repositories
                        <ul style = 'font-size:16px;font-family:Arial'>
                            <li>PubAuth Public Authorization Object</li>
                            <li>demo
                                <ul style = 'font-size:16px;font-family:Arial'>
                                    <li>Customer_EBS</li>
                                    <li>Accounts_Mapping_EBS</li>
                                </ul></li>
                            <li>demo_ofs
                                <ul style = 'font-size:16px;font-family:Arial'>
                                    <li>Customer_EBS</li>
                                    <li>Accounts_Mapping_EBS</li>
                            </ul></li>
                        </ul>
                        <li>Users
                            <ul style = 'font-size:16px;font-family:Arial'>
                                <li>SupportUsers
                                    <ul style = 'font-size:16px;font-family:Arial'>
                                        <li>cgadmin  /* Compute Group admin */</li>
                                    </ul>
                                    <li>BusinessUsers
                                        <ul style = 'font-size:16px;font-family:Arial'>
                                            <li>data_engineer</li>
                                            <li>data_scientist</li>
                                        </ul></li>
                            </ul></li>
                </ul></li>
        </ul></li>
    </ul>

<b style = 'font-size:24px;font-family:Arial;color:#E37C4D'>Naming Standards</b>
   
<p style = 'font-size:20px;font-family:Arial;color:#E37C4D'>Compute Group (CG) naming standard</p>

<p style = 'font-size:16px;font-family:Arial'>CG_<i>BusGrpName_type</i></p>

<p style = 'font-size:16px;font-family:Arial'>where <i>BusGrpName</i>  Business Group (if more than 1 CG, reflect in name)</p>
<p style = 'font-size:16px;font-family:Arial'>    <i>type</i>        Compute Group type (STD/ANL) (ie: Standard/Analytic)</p>
      
<p style = 'font-size:16px;font-family:Arial'> eg: CG_BusGrpA_STD<br>
eg: CG_BusGrpA_ANL</p>


<p style = 'font-size:20px;font-family:Arial;color:#E37C4D'>Compute Group Role (CR) naming standard</p>
<p style = 'font-size:16px;font-family:Arial'>CR_<i>BusGrpName_type</i> <br>
eg: CR_BusGrpA_STD<br>
eg: CR_BusGrpA_ANL</p>


<p style = 'font-size:20px;font-family:Arial;color:#E37C4D'>Compute Group Profile (CP) naming standard</p>
<p style = 'font-size:16px;font-family:Arial'>CP_<i>BusGrpName_type_n_size</i><br>
    where <i>BusGrpName</i>  Business Group (if more than 1 CG, reflect in name)<br>
    <i>type</i>       Compute Group type (STD/ANL)<br>
    <i>n</i>           Compute Profile idendifier (n=1-9)<br>
    <i>size</i>        Compute Cluster t-shirt size (TNY/SML/MED/LRG/1XL/2XL)<br>

eg: CP_BusGrpA_STD_1_SML<br>
eg: CP_BusGrpA_STD_2_MED<br>
eg: CP_BusGrpA_ANL_1_SML</p>

<hr>

<b style = 'font-size:24px;font-family:Arial;color:#E37C4D'>Environment for Demo</b>

<p style = 'font-size:16px;font-family:Arial'><b>vars.json</b> is structured as follows for the demonstration:</p>

```json
{
    "environment":{"host":"54.69.11.56"},      
    "hierarchy":{
        "DBC":{"username":"DBC","password":"demo_dbc"},
        "SYSDBA":{"username":"SYSDBA", "password":"password"},
        "users":{"support_users":[{"username":"cgadmin", "password":"password"}],
                "business_users":[{"username":"data_engineer", 
                                   "password":"password", 
                                   "role":"CR_BusGrpA_STD",
                                   "compute_group":"CG_BUSGRPA_STD"}, 
                               {"username":"data_scientist", 
                                "password":"password", 
                                "role":"CR_BusGrpA_ANL", 
                                "compute_group":"CG_BUSGRPA_ANL"}]},
        "compute_groups":[{"name":"CG_BusGrpA_STD", "type":"STANDARD", "profiles":
                           [{"name":"CP_BusGrpA_STD_1_SML","type":"STANDARD", "size":"TD_COMPUTE_SMALL", "min":"1", "max":"1"}]}, 
                          {"name":"CG_BusGrpA_ANL", "type":"ANALYTIC", "profiles":
                           [{"name":"CP_BusGrpA_ANL_1_SML","type":"ANALYTIC","size":"TD_COMPUTE_SMALL", "min":"1", "max":"1"}]}],
        "compute_group_roles":[{"name":"CR_BusGrpA_STD", "type":"STANDARD"}, 
                               {"name":"CR_BusGrpA_ANL", "type":"ANALYTIC"}],
        "repositories":{"name":"Repositories", 
                        "perm":"5e11",
                       "databases":[{"name":"demo", "perm":"2e11", "default_storage":"TD_NDSSTORAGE"}, 
                                   {"name":"demo_ofs", "perm":"2e11", "default_storage":"TD_OFSSTORAGE"}]}}

}
```

In [1]:
# Import the minimal number of packages

import warnings
warnings.filterwarnings('ignore')

import json
import pandas as pd
import teradatasql

from teradataml import *

In [2]:
# load vars json
with open('vars.json', 'r') as f:
    session_vars = json.load(f)


## Section 1: Environment Setup ## 
### steps overview ###

01) Create TD admin super user (sysdba) and grant privileges   [as dbc]
02) Create User hierachy & Compute Group admin (cgadmin)       [as sysdba]
03) Grant Compute Group admin (cgadmin) privileges             [as dbc]
04) Create Environment database hierachy                       [as sysdba]
05) Create user profiles                                       [as sysdba]
06) Create Roles                                               [as sysdba]
07) Grant privileges to Roles                                  [as sysdba]
08) Create Compute Groups / Compute Profiles                   [as cgadmin]

In [3]:
# /* -------------------------------------------------------- */
# -- Perform this as DBC.
# -- Create Super User (SYSDBA). Parent of hierarchy.
# /* -------------------------------------------------------- */

dbc_name = session_vars['hierarchy']['DBC']['username']
dbc_pwd = session_vars['hierarchy']['DBC']['password']
name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']
perm = session_vars['hierarchy']['SYSDBA']['perm']
spool = session_vars['hierarchy']['SYSDBA']['spool']


with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = dbc_name, 
                     password = dbc_pwd) as con:
    cur = con.cursor()
    
    qry = f'''
        CREATE USER {name} FROM DBC
          AS PERM  = {perm}          /* 800GB */
            ,SPOOL = {spool}          /* 800GB */
            ,PASSWORD = "{pwd}"
            ,ACCOUNT = ('$M')
            ,TIME ZONE = '00:00'   /* UDT */
            ,DEFAULT ROLE = ALL  ;
        '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5612") >= 1:
            pass
        else:
            raise
            
    
    queries = [f'''
        --Grant All privileges on SYSDBA to itself.
        GRANT all on "{name}" to "{name}" WITH GRANT OPTION;
        ''', 
              f'''
        --Grant system-level privileges to SYSDBA.
        GRANT MONRESOURCE, MONSESSION, ABORTSESSION, SETSESSRATE, SETRESRATE, REPLCONTROL, 
              CREATE PROFILE, CREATE ROLE, DROP PROFILE, DROP ROLE 
            to "{name}" WITH GRANT OPTION;
        ''', 
              f'''GRANT EXECUTE, SELECT, STATISTICS, SHOW on DBC to "{name}" WITH GRANT OPTION;''', 
              f'''GRANT UDTTYPE, UDTMETHOD on SYSUDTLIB to "{name}" WITH GRANT OPTION;''', 
              f'''GRANT SELECT, INSERT, UPDATE, DELETE on "Sys_Calendar" to "{name}" WITH GRANT OPTION;''',
              f'''GRANT SELECT, EXECUTE FUNCTION, EXECUTE PROCEDURE on TD_SYSFNLIB to "{name}" WITH GRANT OPTION;''',
              f'''GRANT SELECT, EXECUTE FUNCTION, EXECUTE PROCEDURE on TD_MLDB to "{name}" WITH GRANT OPTION;''',
              f'''GRANT SELECT, EXECUTE FUNCTION, EXECUTE PROCEDURE on syslib to "{name}" WITH GRANT OPTION;''', 
              f'''GRANT EXECUTE FUNCTION on TD_SYSFNLIB.READ_NOS to "{name}" WITH GRANT OPTION;''', 
              f'''GRANT CREATE DATASET SCHEMA on SYSUDTLIB to "{name}" WITH GRANT OPTION;''', 
              f'''GRANT SELECT on TD_METRIC_SVC to "{name}" WITH GRANT OPTION;''',
              f'''GRANT SELECT, EXECUTE FUNCTION, EXECUTE PROCEDURE on SYSSPATIAL to {name} WITH GRANT OPTION;''', 
              f'''GRANT ALL ON retail_sample_data to "{name}" WITH GRANT OPTION;''', 
              f'''
        /* Grant SYSDBA the privileges to grant others to System Roles, except TD_COMPUTE_CLUSTER_ADMIN. */
        /* This is to lockdown who may administer Computer Groups.                                        */ 
        GRANT  TD_USER_ADMIN
              ,TD_DATA_SCIENTIST
              ,TD_FLOW_COMPOSER
              ,TD_CURRENT_QUERIES_ADMIN
              ,TD_CURRENT_QUERIES_VIEW
              ,TD_QUERY_HISTORY_VIEW
              ,DS_ADMIN
              ,DS_CITIZEN
              ,DS_PROVIDER
            to {name} WITH ADMIN OPTION;
        ''', 
              f'''GRANT LOGON ON ALL TO {name} WITH NULL PASSWORD;''']
    for qry in queries:
        cur.execute(qry)

In [4]:
#/* -------------------------------------------------------- */
#-- Perform this as SYSDBA.
#-- Create User hierachy
#/* -------------------------------------------------------- */

name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

user_perm = session_vars['hierarchy']['users']['perm']
user_spool = session_vars['hierarchy']['users']['spool']

# calculate the amount of perm for each of
# the business users (.75) and support users (.25) hierarchy:

bus_perm = str(int(float(user_perm)*.75))
sup_perm = str(int(float(user_perm)*.25))


with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    qry = f'''
        CREATE USER "Users" FROM SYSDBA
          AS PERM  = {user_perm}       /*   30GB */
            ,SPOOL = {user_spool}      /* 100GB */
            ,PASSWORD = "{pwd}"
            ,ACCOUNT = ('$M')
            ,TIME ZONE='00:00'
            ,DEFAULT ROLE=ALL;
            '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5612") >= 1:
            pass
        else:
            raise
    
    qry = f'''
    CREATE USER "BusinessUsers" FROM Users
      AS PERM  = {bus_perm}       /*   20GB */
        ,SPOOL = {user_spool}      /* 100GB */
        ,PASSWORD = "{pwd}"
        ,ACCOUNT = ('$M')
        ,TIME ZONE = '00:00'
        ,DEFAULT ROLE = ALL ;
    '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5612") >= 1:
            pass
        else:
            raise
    
    qry = f'''
    CREATE USER "SupportUsers" FROM Users
      AS PERM =  {sup_perm}      /*   10GB */
        ,SPOOL = {user_spool}      /* 100GB */
        ,PASSWORD = "{pwd}"
        ,ACCOUNT = ('$M')
        ,TIME ZONE = '00:00'
        ,DEFAULT ROLE = ALL;
        '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5612") >= 1:
            pass
        else:
            raise
    
    # create support users from array of support_users
    for u in session_vars['hierarchy']['users']['support_users']:
        qry = f'''
        /* Create Compute Group administrator */
        CREATE USER {u['username']} FROM SupportUsers
          AS PERM = 0       
            ,SPOOL = {user_spool}       /* 10GB */
            ,ACCOUNT = ('$M')
            ,DEFAULT ROLE = ALL
            ,PASSWORD = "{u['password']}" ;
        '''
        try:
            cur.execute(qry)
        except Exception as e:
            # check if user exists
            if str(e.args).find("Error 5612") >= 1:
                pass
            else:
                raise

In [5]:
#/* -------------------------------------------------------- */
#-- Perform this as *** DBC ***.
#-- Grant privileges to Compute Group administrator. 
#-- NB: To lockdown who may create Compute Clusters, there is
#--     intentionally only one CG admin.
#/* -------------------------------------------------------- */

dbc_name = session_vars['hierarchy']['DBC']['username']
dbc_pwd = session_vars['hierarchy']['DBC']['password']


with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = dbc_name, 
                     password = dbc_pwd) as con:
    cur = con.cursor()
    
    # iterate over all support users
    for u in session_vars['hierarchy']['users']['support_users']:
        
        queries = [f'''
        -- Compute Group super user ONLY.
        GRANT TD_USER_ADMIN, TD_COMPUTE_CLUSTER_ADMIN, TD_FLOW_COMPOSER, TD_CURRENT_QUERIES_ADMIN, DS_ADMIN TO {u['username']};
        ''', 
                  f'''GRANT SELECT ON DBC TO {u['username']};''', 
                  f'''GRANT DROP COMPUTE PROFILE to "{u['username']}" WITH GRANT OPTION;''',
                  f'''GRANT CREATE COMPUTE PROFILE to "{u['username']}" WITH GRANT OPTION;''', 
                  f'''grant CREATE COMPUTE GROUP to "{u['username']}" WITH GRANT OPTION;''',
                  f'''grant DROP COMPUTE GROUP to "{u['username']}" WITH GRANT OPTION;''', 
                  f'''GRANT LOGON ON ALL TO {u['username']} WITH NULL PASSWORD;''']
        for qry in queries:
            cur.execute(qry)

In [6]:
# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Create Environment database hierachy
# -- Root database contains a PubAuth Authorization object for
# -- Anonymous NOS access
# /* -------------------------------------------------------- */


name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    # Create root database
    qry = f'''
    CREATE DATABASE {session_vars['hierarchy']['repositories']['name']} from {name} 
      AS PERM = {session_vars['hierarchy']['repositories']['perm']} ;
      '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5612") >= 1:
            pass
        else:
            raise
    
    # Create root Public Auth object with NULL username and password
    qry = f'''REPLACE AUTHORIZATION {session_vars['hierarchy']['repositories']['name']}.PubAuth
            user '' password '';'''
    cur.execute(qry)
    
    # Create child databases
    for d in session_vars['hierarchy']['repositories']['databases']:
        qry = f'''
        CREATE DATABASE {d['name']} from Repositories  AS
          DEFAULT STORAGE = {d['default_storage']} OVERRIDE ON ERROR,
          PERM = {d['perm']};
        '''
        try:
            cur.execute(qry)
        except Exception as e:
            # check if user exists
            if str(e.args).find("Error 5612") >= 1:
                pass
            # check if object exists - "perm space"
            elif str(e.args).find("Error 3541") >= 1:
                pass
            else:
                raise
        
        qry = f'''GRANT Select on DBC to {d['name']} with grant option;'''
        cur.execute(qry)
        
        qry = f'''GRANT Select on Sys_Calendar to {d['name']} with grant option;'''
        cur.execute(qry)
        
        qry = f'''GRANT Select on TD_METRIC_SVC to {d['name']} with grant option;'''
        cur.execute(qry)
        
        qry = f'''GRANT EXECUTE on retail_sample_data.demo_Auth_NOS to "{d['name']}" WITH GRANT OPTION;'''
        cur.execute(qry)
        
        # Grant execute to the PubAuth object
        qry = f'''GRANT EXECUTE on {session_vars['hierarchy']['repositories']['name']}.PubAuth to "{d['name']}" WITH GRANT OPTION;'''
        cur.execute(qry)

In [7]:
# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Create Profiles
# /* -------------------------------------------------------- */

name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

user_spool = session_vars['hierarchy']['users']['spool']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    qry = f'''
        CREATE PROFILE "P_BusGrpA" AS
        SPOOL={user_spool}      /* 100GB */
        TEMPORARY=1E8   /* 100MB */
        ACCOUNT=NULL
        DEFAULT DATABASE=NULL ;
        '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5652") >= 1:
            pass
        else:
            raise
    
    qry = f'''
        CREATE PROFILE "P_SupportUsers" AS
        SPOOL={user_spool}      /* 100GB */
        TEMPORARY=1E8   /* 100MB */
        ACCOUNT=NULL
        DEFAULT DATABASE=NULL ;
        '''
    try:
        cur.execute(qry)
    except Exception as e:
        # check if user exists
        if str(e.args).find("Error 5652") >= 1:
            pass
        else:
            raise

In [8]:
# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Create Roles for Compute Groups admin, General TD access, NOS, etc.
# /* -------------------------------------------------------- */

name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    for d in session_vars['hierarchy']['compute_group_roles']:
        
        qry = f'''create role {d['name']};'''
        try:
            cur.execute(qry)
        except Exception as e:
            # check if user exists
            if str(e.args).find("Error 5612") >= 1:
                pass
            else:
                raise
    
    queries = ['''
    -- Create a Teradata general admin role 
    create role R_TD_Admin; ''', 
               '''
    -- Create Roles for general TD access rights 
    create role R_TD_General;''', 
              '''
    -- Create Roles for NOS access rights 
    create role R_NOS;''', 
              '''
    -- Create ANALYTICS Role
    create role R_Analytics_1;''', 
              '''
    -- Create Demo Role (Read only)
    create role R_Demo_R;''', 
              '''
    -- Create Demo Role (Read/Write)
    create role R_Demo_RW;''']
    
    for qry in queries:
        try:
            cur.execute(qry)
        except Exception as e:
            # check if user exists
            if str(e.args).find("Error 5612") >= 1:
                pass
            else:
                raise

In [9]:
# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Grant privileges to Roles.
# /* -------------------------------------------------------- */


name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    queries = ['''
    /* R_TD_Admin */
    GRANT EXECUTE, SELECT, STATISTICS, SHOW ON "DBC" to R_TD_Admin;''', 
              '''GRANT  TD_CURRENT_QUERIES_ADMIN to R_TD_Admin;''', 
              '''
    /* R_TD_General */
    GRANT SELECT ON TD_METRIC_SVC to R_TD_General;''', 
              '''GRANT TD_CURRENT_QUERIES_VIEW to R_TD_General;''', 
              '''GRANT TD_QUERY_HISTORY_VIEW   to R_TD_General;''', 
              '''GRANT EXECUTE FUNCTION ON TD_SYSFNLIB to R_TD_General;''',
              '''GRANT EXECUTE FUNCTION ON TD_MLDB to R_TD_General;''', 
              '''GRANT SELECT ON DBC to R_TD_General;''', 
              '''GRANT SELECT, EXECUTE FUNCTION, EXECUTE PROCEDURE ON syslib to R_TD_General;''',
              '''GRANT SELECT, EXECUTE FUNCTION, EXECUTE PROCEDURE ON sysspatial to R_TD_General;''',
              '''
    /* R_NOS */
    GRANT EXECUTE FUNCTION ON TD_SYSFNLIB.READ_NOS  to R_NOS;''', 
              '''GRANT EXECUTE FUNCTION ON TD_SYSFNLIB.WRITE_NOS to R_NOS;''', 
              '''GRANT CREATE DATASET SCHEMA on SYSUDTLIB to R_NOS;''', 
              '''
    /* R_Analytics_1 */
    GRANT TD_DATA_SCIENTIST TO R_Analytics_1;''',
               
              '''/* R_Demo_R */
                GRANT Select  on demo to R_Demo_R ; ''', 
               
               '''/* R_Demo_R */
                GRANT Select  on demo_ofs to R_Demo_R ;''',
               
              '''
    /* R_Demo_RW */
    GRANT Create Table, Drop Table, Insert, Update, Delete, Select,
      Create AUTHORIZATION on demo to R_Demo_RW;''',
               '''
    /* R_Demo_RW */
    GRANT Create Table, Drop Table, Insert, Update, Delete, Select,
      Create AUTHORIZATION on demo_ofs to R_Demo_RW;''',
             '''GRANT Create View, Drop View, Select on demo to R_Demo_RW;''',
              '''GRANT Create View, Drop View, Select on demo_ofs to R_Demo_RW;''']
    
    for qry in queries:
        try:
            cur.execute(qry)
        except Exception as e:
            # check if user exists
            if str(e.args).find("Error 5612") >= 1:
                pass
            else:
                raise

In [10]:
# /* -------------------------------------------------------- */
# -- Perform this as cgadmin
# -- Create Compute Groups / Compute Profiles
# /* -------------------------------------------------------- */

# /* Learnings: 
# --  1) Some of these statements do not run under ODBC or .NET (only JDBC) 
# --  2) If you create a Compute Profile "INITIALLY_SUSPENDED", it goes through its
# --     states of "Deploying", "Hibernating", "Hibernated". This takes about 10 mins.
# --     Once it's in the "Hibernated" (suspend) state, currently we are not able to
# --     "Resume" it. Therefore, start/stop the CG by Create/Drop the Compute Profile.
# */

name = session_vars['hierarchy']['users']['support_users'][0]['username']
pwd = session_vars['hierarchy']['users']['support_users'][0]['password']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    # iterate through the groups and profiles
    for cg in session_vars['hierarchy']['compute_groups']:
        
        qry = f'''CREATE COMPUTE GROUP {cg['name']} USING QUERY_STRATEGY('{cg['type']}');'''
        try:
            cur.execute(qry)
        except Exception as e:
            # check if group exists
            if str(e.args).find("Error 4822") >= 1:
                pass
            else:
                raise
        
        # iterate over each child profile in the group
        for cp in cg['profiles']:
            
            qry = f'''
            /* This profile is configured to be available from 9am to 9pm EDT. */
            CREATE COMPUTE PROFILE {cp['name']} IN COMPUTE GROUP {cg['name']}
            ,INSTANCE = {cp['size']}
            ,INSTANCE TYPE = {cp['type']}   
             USING
                 MIN_COMPUTE_COUNT ({cp['min']})
                 MAX_COMPUTE_COUNT ({cp['max']})
                 SCALING_POLICY ('STANDARD')
                 START_TIME ('0 13 * * MON-FRI')
                 END_TIME ('0 01 * * MON-SAT')
                 COOLDOWN_PERIOD (30) ;
            '''
            try:
                cur.execute(qry)
            except Exception as e:
                # check if profile exists
                if str(e.args).find("Error 4826") >= 1:
                    pass
                else:
                    raise

# Section 2 - User Creation #
#####################################################################
## End-User creation/privileges instructions
#####################################################################

In [11]:
# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Create end-users
# -- Recommendation: Create new users under "BusinessUsers"
# /* -------------------------------------------------------- */

name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']
user_perm = session_vars['hierarchy']['users']['perm']

# split up perm space based on the number of users:
# business users are .75 of total user perm
# divide this by the number of users in business users

ind_user_perm = str(int((float(user_perm)*.75) / len(session_vars['hierarchy']['users']['business_users'])))



with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    for u in session_vars['hierarchy']['users']['business_users']:
        
        qry = f'''
        CREATE USER {u['username']} FROM BusinessUsers
         AS PERM =  {ind_user_perm} 
           ,Spool = 0    /* Spool is defined in the Profile */
           ,Profile = "P_BusGrpA"
           ,PASSWORD = "{u['password']}"
           ,ACCOUNT = ('$M')
           ,TIME ZONE = '00:00'
           ,DEFAULT ROLE = ALL
           ,COMPUTE GROUP = {u['compute_group']};
        '''
        try:
            cur.execute(qry)
        except Exception as e:
            # check if user exists
            if str(e.args).find("Error 5612") >= 1:
                pass
            else:
                raise
        
        qry = f'''GRANT LOGON ON ALL TO {u['username']} WITH NULL PASSWORD;'''
        cur.execute(qry)
        
        qry = f'''GRANT TD_DATA_SCIENTIST TO {u['username']};'''
        cur.execute(qry)
        
        qry = f'''GRANT TD_FLOW_COMPOSER TO {u['username']};'''
        cur.execute(qry)
        
        qry = f'''GRANT DS_ADMIN TO {u['username']};'''
        cur.execute(qry)
        
        qry = f'''GRANT EXECUTE PROCEDURE ON {u['username']} TO {u['username']};'''
        cur.execute(qry)

        qry = f'''GRANT CREATE PROCEDURE ON {u['username']} TO {u['username']};'''
        cur.execute(qry)

In [12]:
# /* -------------------------------------------------------- */
# -- Perform this as CGADMIN.
# -- Grant COMPUTE GROUP to every user
# /* -------------------------------------------------------- */

name = session_vars['hierarchy']['users']['support_users'][0]['username']
pwd = session_vars['hierarchy']['users']['support_users'][0]['password']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    for u in session_vars['hierarchy']['users']['business_users']:
        
        qry = f'''GRANT COMPUTE GROUP {u['compute_group']} TO {u['username']}'''
        cur.execute(qry)

In [14]:

# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Grant Roles to User (including access to Compute Groups)
# /* -------------------------------------------------------- */

# --##############################################################################
# -- Refer to the environment setup file (VCLE_environment_setup_vXX) for 
# -- details on privileges assigned to each Role. 
# -- This is an overview.
# --
# -- ROLENAME                RIGHTS
# --                         
# -- R_TD_Admin              Access to DBC and TD_CURRENT_QUERIES_ADMIN
# -- R_TD_General            Access to MSS, TD_SYSFNLIB, SYSLIB, Select on DBC
# -- R_NOS                   Access to TD_SYSFNLIB.READ_NOS, CREATE DATASET SCHEMA on SYSUDTLIB
# -- R_Analytics_1           TD_DATA_SCIENTIST
# -- R_Demo_R              Read (only) on Demo databases
# -- R_Demo_RW             Read/Write  on Demo databases	
				   
# -- CR_BusGrpA_STD  Non-admin privileges to use Standard Compute Group CG_BusGrpA_STD
# -- CR_BusGrpA_ANL  Non-admin privileges to use Analytic Compute Group CG_BusGrpA_ANL
# --##############################################################################

name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    for u in session_vars['hierarchy']['users']['business_users']:
        
        queries = [f'''
        -- Grant Non-Admin user to the Compute Group (CG) Roles
        -- NB: User cannot use the CG until it is "SET" as their default CG. 
        GRANT {u['role']} to {u['username']};''',
                  f'''
        -- Grant other Roles to user
        GRANT  R_TD_General   to {u['username']} ;
        ''', 
                  f'''GRANT  R_Analytics_1 to {u['username']};''', 
                  f'''GRANT R_NOS to {u['username']};''', 
                  f'''GRANT R_Demo_RW to {u['username']} ;''', 
                  f'''
        --special grant to get access to the NOS AUTH in retail_sample_data
        GRANT ALL ON retail_sample_data TO {u['username']} WITH GRANT OPTION;''', 
                  f'''grant execute on retail_sample_data.demo_Auth_NOS to "{u['username']}" WITH GRANT OPTION;''',
                   f'''
                   --special grant to get access to the root PubAuth
                   GRANT EXECUTE on {session_vars['hierarchy']['repositories']['name']}.PubAuth to "{u['username']}" WITH GRANT OPTION;''',
                   f'''
                   --special grant to WITH GRANT OPTION to demo database
                   GRANT SELECT on demo to "{u['username']}" WITH GRANT OPTION;''',
                   f'''
                   --special grant to WITH GRANT OPTION to demo_ofs database
                   GRANT SELECT on demo_ofs to "{u['username']}" WITH GRANT OPTION;''',
                  f'''
        -- Set default Compute Group to existing user.
        -- NB: This may also be done by the user via "SET SESSION COMPUTE GROUP <CG_Name>;"
        MODIFY user {u['username']} as COMPUTE GROUP = {u['compute_group']} ;''']
        
        for qry in queries:
            cur.execute(qry)

SyntaxError: invalid syntax (3593228674.py, line 52)