<hr>

## Data Loads for Embeddings Demo ##
- **demo_ofs.glove_6b_50d**

In [6]:
# /* -------------------------------------------------------- */
# -- Perform this as SYSDBA.
# -- Load demo_ofs.demo_ofs.glove_6b_50d*  data
# /* -------------------------------------------------------- */

import teradatasql, json

# load vars json
with open('../../vars.json', 'r') as f:
    session_vars = json.load(f)

name = session_vars['hierarchy']['SYSDBA']['username']
pwd = session_vars['hierarchy']['SYSDBA']['password']

bucket = session_vars['environment']['bucket']

with teradatasql.connect(host = session_vars['environment']['host'], 
                     user = name, 
                     password = pwd) as con:
    cur = con.cursor()
    
    try:
        cur.execute('DROP TABLE DEMO_OFS.glove_6B_50d')
    except Exception as e:
        # Table already exists
        if str(e.args).find("3807") >= 1:
            pass
        else:
            raise
            
    
    qry = '''
CREATE MULTISET TABLE DEMO_OFS.glove_6B_50d,
STORAGE = TD_OFSSTORAGE
     (
      doc_id VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC,
      v1 FLOAT,
      v2 FLOAT,
      v3 FLOAT,
      v4 FLOAT,
      v5 FLOAT,
      v6 FLOAT,
      v7 FLOAT,
      v8 FLOAT,
      v9 FLOAT,
      v10 FLOAT,
      v11 FLOAT,
      v12 FLOAT,
      v13 FLOAT,
      v14 FLOAT,
      v15 FLOAT,
      v16 FLOAT,
      v17 FLOAT,
      v18 FLOAT,
      v19 FLOAT,
      v20 FLOAT,
      v21 FLOAT,
      v22 FLOAT,
      v23 FLOAT,
      v24 FLOAT,
      v25 FLOAT,
      v26 FLOAT,
      v27 FLOAT,
      v28 FLOAT,
      v29 FLOAT,
      v30 FLOAT,
      v31 FLOAT,
      v32 FLOAT,
      v33 FLOAT,
      v34 FLOAT,
      v35 FLOAT,
      v36 FLOAT,
      v37 FLOAT,
      v38 FLOAT,
      v39 FLOAT,
      v40 FLOAT,
      v41 FLOAT,
      v42 FLOAT,
      v43 FLOAT,
      v44 FLOAT,
      v45 FLOAT,
      v46 FLOAT,
      v47 FLOAT,
      v48 FLOAT,
      v49 FLOAT,
      v50 FLOAT)
NO PRIMARY INDEX ;
    '''
    cur.execute(qry)
    
    qry = f'''
    Insert into DEMO_OFS.glove_6B_50d 
    SELECT doc_id, v1, v2, v3, v4, v5, v6, v7, v8, v9, v10, 
    v11, v12, v13, v14, v15, v16, v17, v18, v19, v20, v21, 
    v22, v23, v24, v25, v26, v27, v28, v29, v30, v31, v32, 
    v33, v34, v35, v36, v37, v38, v39, v40, v41, v42, v43, 
    v44, v45, v46, v47, v48, v49, v50

    FROM
            (
                LOCATION = '/s3/{bucket}.s3.amazonaws.com/DEMO_OFS/GLOVE_6B_50D/manifest.json'
                MANIFEST = 'TRUE'
            ) D;'''
    
    cur.execute(qry)